### ISSUE TITLE
Trying to build include function

### ISSUE THREAD

**Issue by Trilobyte631** [pirple/The-NodeJS-Master-Class#15]
Function helpers.getHTMLAsset  is from the course,  I have created helpers.resolveIncludes to take the HTML string and search for <include>"filename.html"</include> then load the filename.html and return a new string to the browser.

I am getting "undefined" for finalStr  in function below however the string is correct when console logged before the return in helpers.resolveIncludes.  I am certain this is a Scope related issue but have not been able to find the problem for hours now...  

Thank you for any assistance !

// ============================================================
//   Get the contents of an HTML file as a string, and check for and resolve server side includes
// ============================================================
helpers.getHTMLAsset = function(fileName, callback) {
  fileName =
    typeof fileName == "string" && fileName.length > 0 ? fileName : false;
  if (fileName) {
    var publicDir = path.join(__dirname, "/../public/");
    fs.readFile(publicDir + fileName, "utf8", function(err, str) {
      if (!err && str && str.length > 0) {
        var finalStr = "";
        finalStr = helpers.resolveIncludes(str);
        console.log("Received FinalString: " + finalStr);
        callback(false, finalStr);
      } else {
        callback("Filename could be found");
      }
    });
  } else {
    callback("A valid filename name was not specified");
  }
};

// ==================================================================
//   Include files as needed
// =================================================================
helpers.resolveIncludes = function(str) {
  var result = "";

  // Verify we have a valid String
  var str = typeof str == "string" && str.length > 0 ? str : false;
  if (str) {
    var startPos = str.indexOf("<include>");
    if (startPos > -1) {
      // Search for ending </include> tag
      var endPos = str.indexOf("</include>", startPos);
      if (endPos > -1) {
        //console.log("Found closing </include> tag at pos: " + endPos);

        // Extract include file name
        var fileName = str.substring(startPos + 10, endPos - 1);

        // Load the file
        helpers.getHTMLTemplate(fileName, function(err, fileData) {
          if (!err && fileData && fileData.length > 0) {
            // Insert include file
            var strBefore = str.substring(0, startPos);
            var strAfter = str.substring(endPos + 10);

            // New String with file included
            result = strBefore + fileData + strAfter;

            // console.log("Returning: " + str);

            // Callback new String
            return result;
          } else {
            // Error: File not found or File empty
            return str;
          }
        });
      } else {
        // Closing </include> not found
        return str;
      }
    } else {
      // Opening <include> tag not found
      return str;
    }
  } else {
    // String is invalid
    return str;
  }
};

**Comment by marta-krzyk-dev** [comment]
It probably won't solve all the problems, but:

Try adding var before `result`
`var result = strBefore + fileData + strAfter;`

and return the result of `helpers.getHTMLTemplate`, eg.

`// Load the file`
`var template = helpers.getHTMLTemplate() // ...`
`return template;`

Can you post the implementation of helpers.getHTMLTemplate?
