### ISSUE TITLE
fs.truncate with a descriptor is deprecated.

### ISSUE THREAD

**Issue by ghost** [pirple/The-NodeJS-Master-Class#3]
In section three, we create the update functionality and are instructed to use `fs.truncate` but I received a warning from node:

(node:29626) [DEP0081] DeprecationWarning: Using fs.truncate with a file descriptor is deprecated. Please use **fs.ftruncate** with a file descriptor instead.

**Comment by lokyi** [comment]
Looks like you would get this error if you are using node v10 while @pirple-author is targeting Node v8.

Using fs.truncate with a file descriptor will actually call fs.ftruncate, [according to the doc](https://nodejs.org/dist/latest-v8.x/docs/api/fs.html#fs_fs_truncate_path_len_callback)

Maybe it is more appropriate to use fs.ftruncate in production, but for demonstration purposes, using truncate is more intuitive?
